services:
  dev_database:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - dev_database:/var/lib/postgresql/data
    networks:
      - default

  
  dev_influxdb2:
    image: influxdb:2.7.3
    ports:
      - "8086:8086"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: Passw0rd!.
      DOCKER_INFLUXDB_INIT_ORG: dev
      DOCKER_INFLUXDB_INIT_BUCKET: dev
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: admin
    volumes:
      - dev_influxdb2:/var/lib/influxdb2
    networks:
      - default

  dev_grafana:
    image: grafana/grafana-oss
    ports:
      - "3000:3000"
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
      GF_AUTH_ANONYMOUS_ORG_NAME: "Main Org."
      GF_AUTH_DISABLE_LOGIN_FORM: "true"
      GF_AUTH_DISABLE_SIGNOUT_MENU: "true"
      GF_AUTH_PROXY_ENABLED: "true"
      GF_AUTH_PROXY_HEADER_NAME: "X-WEBAUTH-USER"
      GF_AUTH_PROXY_HEADER_PROPERTY: "username"
      GF_AUTH_PROXY_AUTO_SIGN_UP: "true"
      GF_AUTH_PROXY_ENABLE_LOGIN_TOKEN: "true"
      GF_AUTH_PROXY_LOGIN_TOKEN_NAME: "login_token"
      GF_AUTH_PROXY_WHITELIST: "*"
    volumes:
      - dev_grafana:/var/lib/grafana
    networks:
      - default

volumes:
  dev_database:
  dev_influxdb2:
  dev_grafana:

networks:
  default:
    name: dev_network