name: CD - Deploy to Test Server

on:
  workflow_run:
    workflows: ["CI - Image Deploy To Docker Hub"]
    branches: [main]
    types:
      - completed

jobs:
  deploy_to_caprover:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Deploy Image to CapRrover
        uses: caprover/deploy-from-github@v1.1.2
        with:
          server: "${{ secrets.CAPROVER_SERVER }}"
          app: "${{ secrets.CAPROVER_APP_NAME }}"
          token: "${{ secrets.CAPROVER_APP_TOKEN }}"
          image: "${{ secrets.CAPROVER_IMAGE }}:latest"
